"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class EntryStatus(str, Enum):
    r"""Filters to a single status of ledger entry"""
    COMMITTED = 'committed'
    PENDING = 'pending'
