"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import customer as shared_customer
from typing import Optional


@dataclasses.dataclass
class GetCustomersExternalCustomerIDExternalCustomerIDRequest:
    
    external_customer_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'external_customer_id', 'style': 'simple', 'explode': False }})  
    

@dataclasses.dataclass
class GetCustomersExternalCustomerIDExternalCustomerIDResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    customer: Optional[shared_customer.Customer] = dataclasses.field(default=None)
    r"""OK"""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    