"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import amendedevent as shared_amendedevent
from ..shared import amendeventresult as shared_amendeventresult
from dataclasses_json import Undefined, dataclass_json
from orb import utils
from typing import Optional


@dataclasses.dataclass
class AmendEventRequest:
    
    event_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'event_id', 'style': 'simple', 'explode': False }})
    r"""Identical to the `idempotency_key` provided on event ingestion. Uniquely identifies an event in the system."""
    amended_event: Optional[shared_amendedevent.AmendedEvent] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AmendEvent400ApplicationJSONValidationErrors:
    
    idempotency_key: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('idempotency_key'), 'exclude': lambda f: f is None }})
    validation_errors: Optional[list[str]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('validation_errors'), 'exclude': lambda f: f is None }})
    r"""An array of strings corresponding to each validation failure"""
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AmendEvent400ApplicationJSON:
    r"""Bad Request"""
    
    status: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status') }})
    r"""HTTP Code"""
    title: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('title') }})
    r"""Error message"""
    type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    validation_errors: list[AmendEvent400ApplicationJSONValidationErrors] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('validation_errors') }})
    r"""Contains all failing validation events."""
    

@dataclasses.dataclass
class AmendEventResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    amend_event_400_application_json_object: Optional[AmendEvent400ApplicationJSON] = dataclasses.field(default=None)
    r"""Bad Request"""
    amend_event_result: Optional[shared_amendeventresult.AmendEventResult] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    