"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import subscriptionschedule as shared_subscriptionschedule
from typing import Optional


@dataclasses.dataclass
class FetchSubscriptionScheduleRequest:
    
    subscription_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'subscription_id', 'style': 'simple', 'explode': False }})
    

@dataclasses.dataclass
class FetchSubscriptionScheduleResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    subscription_schedule: Optional[shared_subscriptionschedule.SubscriptionSchedule] = dataclasses.field(default=None)
    r"""OK"""
    