"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import customer_balance_transaction as shared_customer_balance_transaction
from dataclasses_json import Undefined, dataclass_json
from orb import utils
from typing import Any, Optional


@dataclasses.dataclass
class GetCustomersCustomerIDBalanceTransactionsRequest:
    
    customer_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'customer_id', 'style': 'simple', 'explode': False }})  
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class GetCustomersCustomerIDBalanceTransactions200ApplicationJSON:
    r"""OK"""
    
    data: Optional[list[shared_customer_balance_transaction.CustomerBalanceTransaction]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data'), 'exclude': lambda f: f is None }})  
    pagination_metadata: Optional[dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('pagination_metadata'), 'exclude': lambda f: f is None }})  
    

@dataclasses.dataclass
class GetCustomersCustomerIDBalanceTransactionsResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    get_customers_customer_id_balance_transactions_200_application_json_object: Optional[GetCustomersCustomerIDBalanceTransactions200ApplicationJSON] = dataclasses.field(default=None)
    r"""OK"""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    