"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import event as shared_event
from ..shared import ingestionresponse as shared_ingestionresponse
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from orb import utils
from typing import Optional

class IngestDebug(str, Enum):
    r"""Flag to enable additional debug information in the endpoint response"""
    TRUE = 'true'
    FALSE = 'false'


@dataclasses.dataclass
class IngestRequest:
    
    backfill_id: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'backfill_id', 'style': 'form', 'explode': True }})
    r"""If this ingestion request is part of a backfill, this parameter ties the ingested events to the backfill"""
    debug: Optional[IngestDebug] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'debug', 'style': 'form', 'explode': True }})
    r"""Flag to enable additional debug information in the endpoint response"""
    request_body: Optional[list[shared_event.Event]] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Ingest400ApplicationJSONValidationErrors:
    
    idempotency_key: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('idempotency_key'), 'exclude': lambda f: f is None }})
    validation_errors: Optional[list[str]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('validation_errors'), 'exclude': lambda f: f is None }})
    r"""An array of strings corresponding to each validation failure"""
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Ingest400ApplicationJSON:
    r"""Bad Request"""
    
    status: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status') }})
    r"""HTTP Code"""
    title: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('title') }})
    r"""Error message"""
    type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    validation_errors: list[Ingest400ApplicationJSONValidationErrors] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('validation_errors') }})
    r"""Contains all failing validation events."""
    

@dataclasses.dataclass
class IngestResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    ingest_400_application_json_object: Optional[Ingest400ApplicationJSON] = dataclasses.field(default=None)
    r"""Bad Request"""
    ingestion_response: Optional[shared_ingestionresponse.IngestionResponse] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    