"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import customer as shared_customer
from typing import Optional


@dataclasses.dataclass
class PostCustomersResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    customer: Optional[shared_customer.Customer] = dataclasses.field(default=None)
    r"""Created"""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    