"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import subscription as shared_subscription
from typing import Optional


@dataclasses.dataclass
class PostSubscriptionsSubscriptionIDUnschedulePendingPlanChangesRequest:
    
    subscription_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'subscription_id', 'style': 'simple', 'explode': False }})  
    

@dataclasses.dataclass
class PostSubscriptionsSubscriptionIDUnschedulePendingPlanChangesResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    subscription: Optional[shared_subscription.Subscription] = dataclasses.field(default=None)
    r"""OK"""  
    