name: Generate
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force the generation of the SDKs
        type: boolean
        default: false
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v14
    with:
      force: ${{ github.event.inputs.force }}
      languages: '- python'
      mode: pr
      openapi_doc_auth_header: x-api-key
      openapi_doc_location: ./openapi/openapi.yaml
      publish_python: true
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      openapi_doc_auth_token: ${{ secrets.SPEAKEASY_API_KEY }}
      pypi_token: ${{ secrets.PYPI_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_PROD_API_KEY }}
